version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: icdev_db
    env_file: ./.env
    expose: [3306]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=icDev
      - MYSQL_PORT=3306
    ports:
      - "$DB_LOCAL_PORT:3306" 
    networks:
      icDev_network:
        aliases:
            - db
    volumes:
      - database:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/my.cnf
      - ./db:/var/lib/mysql-files
  
  testdb:
    image: mysql:8.0
    container_name: icdev_test_db
    env_file: ./.env
    expose: [3305]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=icDevTest
      - MYSQL_TCP_PORT=3305
    ports:
      - "$TEST_DB_LOCAL_PORT:3305" 
    networks:
      icDev_network:
        aliases:
            - testdb
    volumes:
      - test_database:/var/lib/mysql
      - ./db/test/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/test/my.cnf:/etc/my.cnf
      - ./db:/var/lib/mysql-files
      
  app:
    build: ./api
    image: node:18-alpine
    container_name: icdev_app
    command: npm run dev
    working_dir: /api
    restart: on-failure
    env_file: ./.env
    expose: [8000]
    environment:
      - APP_ENV=$APP_ENV
      - PORT=8000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=icDev
      - DB_PORT=3306
      - TEST_DB_HOST=testdb
      - TEST_DB_USER=root
      - TEST_DB_PASSWORD=root
      - TEST_DB_NAME=icDevTest
      - TEST_DB_PORT=3305
    networks:
      icDev_network:
        aliases:
            - app
    volumes:
      - ./api:/api:cached
    depends_on:
      db:
        condition: service_started
      testdb:
        condition: service_started
  
  proxy:
    build: ./nginx
    image: nginx:stable
    container_name: icdev_proxy
    hostname: nginx
    ports:
      - "8080:80" 
    networks:
      icDev_network:
        aliases:
            - proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started

networks:
  icDev_network:
    name: icDev_network
    driver: bridge

volumes: 
  database:
    name: icDev_database
  test_database:
    name: icDevTest_database